# IDX Exchange DS Internship - Week Three - Data Preprocessing

* Handle missing values (decide whether to drop, impute, or flag).
* Convert categorical fields to numeric (encoding).
* Normalize numerical features if needed.
* Create train/test split: use the most recent month of available data as the test set, and the X months immediately preceding it as the training set. X is not fixed — treat the training window length as a tunable choice and experiment to determine the optimal value of X.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.preprocessing import TargetEncoder

## Import Data

In [2]:
# Read in sold: Jan, 2024 - April, 2026

sold_24_1 = pd.read_csv("../csv/CRMLSSold202401_filled.csv")
sold_24_2 = pd.read_csv("../csv/CRMLSSold202402.csv")
sold_24_3 = pd.read_csv("../csv/CRMLSSold202403_filled.csv")
sold_24_4 = pd.read_csv("../csv/CRMLSSold202404_filled.csv", low_memory=False)
sold_24_5 = pd.read_csv("../csv/CRMLSSold202405_filled.csv")
sold_24_6 = pd.read_csv("../csv/CRMLSSold202406_filled.csv")
sold_24_7 = pd.read_csv("../csv/CRMLSSold202407_filled.csv")
sold_24_8 = pd.read_csv("../csv/CRMLSSold202408.csv")
sold_24_9 = pd.read_csv("../csv/CRMLSSold202409.csv")
sold_24_10 = pd.read_csv("../csv/CRMLSSold202410.csv")
sold_24_11 = pd.read_csv("../csv/CRMLSSold202411.csv")
sold_24_12 = pd.read_csv("../csv/CRMLSSold202412.csv")
sold_25_1 = pd.read_csv("../csv/CRMLSSold202501_filled.csv")
sold_25_2 = pd.read_csv("../csv/CRMLSSold202502.csv")
sold_25_3 = pd.read_csv("../csv/CRMLSSold202503.csv")
sold_25_4 = pd.read_csv("../csv/CRMLSSold202504.csv")
sold_25_5 = pd.read_csv("../csv/CRMLSSold202505.csv")
sold_25_6 = pd.read_csv("../csv/CRMLSSold202506.csv", low_memory=False)
sold_25_7 = pd.read_csv("../csv/CRMLSSold202507.csv")
sold_25_8 = pd.read_csv("../csv/CRMLSSold202508.csv")
sold_25_9 = pd.read_csv("../csv/CRMLSSold202509.csv")
sold_25_10 = pd.read_csv("../csv/CRMLSSold202510.csv")
sold_25_11 = pd.read_csv("../csv/CRMLSSold202511.csv")
sold_25_12 = pd.read_csv("../csv/CRMLSSold202512.csv")
sold_26_1 = pd.read_csv("../csv/CRMLSSold202601.csv", low_memory=False)
sold_26_2 = pd.read_csv("../csv/CRMLSSold202602.csv")
sold_26_3 = pd.read_csv("../csv/CRMLSSold202603.csv")
sold_26_4 = pd.read_csv("../csv/CRMLSSold202604.csv")

In [3]:
# Add a column that notes each month the dataset is pulled from

sold_24_1["PropertyMonth"] = "2024-01-01"
sold_24_2["PropertyMonth"] = "2024-02-01"
sold_24_3["PropertyMonth"] = "2024-03-01"
sold_24_4["PropertyMonth"] = "2024-04-01"
sold_24_5["PropertyMonth"] = "2024-05-01"
sold_24_6["PropertyMonth"] = "2024-06-01"
sold_24_7["PropertyMonth"] = "2024-07-01"
sold_24_8["PropertyMonth"] = "2024-08-01"
sold_24_9["PropertyMonth"] = "2024-09-01"
sold_24_10["PropertyMonth"] = "2024-10-01"
sold_24_11["PropertyMonth"] = "2024-11-01"
sold_24_12["PropertyMonth"] = "2024-12-01"
sold_25_1["PropertyMonth"] = "2025-01-01"
sold_25_2["PropertyMonth"] = "2025-02-01"
sold_25_3["PropertyMonth"] = "2025-03-01"
sold_25_4["PropertyMonth"] = "2025-04-01"
sold_25_5["PropertyMonth"] = "2025-05-01"
sold_25_6["PropertyMonth"] = "2025-06-01"
sold_25_7["PropertyMonth"] = "2025-07-01"
sold_25_8["PropertyMonth"] = "2025-08-01"
sold_25_9["PropertyMonth"] = "2025-09-01"
sold_25_10["PropertyMonth"] = "2025-10-01"
sold_25_11["PropertyMonth"] = "2025-11-01"
sold_25_12["PropertyMonth"] = "2025-12-01"
sold_26_1["PropertyMonth"] = "2026-01-01"
sold_26_2["PropertyMonth"] = "2026-02-01"
sold_26_3["PropertyMonth"] = "2026-03-01"
sold_26_4["PropertyMonth"] = "2026-04-01"

In [4]:
# Combine into one dataframe

sold_list = [sold_24_1, sold_24_2, sold_24_3, sold_24_4, sold_24_5, sold_24_6,
                 sold_24_7, sold_24_8, sold_24_9, sold_24_10, sold_24_11, sold_24_12,
                 sold_25_1, sold_25_2, sold_25_3, sold_25_4, sold_25_5, sold_25_6,
                 sold_25_7, sold_25_8, sold_25_9, sold_25_10, sold_25_11, sold_25_12, 
                 sold_26_1, sold_26_2, sold_26_3, sold_26_4]
sold = pd.concat(sold_list)

In [5]:
# Filter on PropertyType == Residential and PropertySubType == SingleFamilyResidence

dataset = sold[(sold["PropertyType"] == "Residential") & (sold["PropertySubType"] == "SingleFamilyResidence")]
dataset = dataset.drop(columns = ["PropertyType", "PropertySubType"])

In [6]:
dataset.head()

,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,latfilled,lonfilled,PropertyMonth,BuyerAgentAOR,ListAgentAOR,OriginatingSystemName,OriginatingSystemSubName
5,NaN,False,NaN,NaN,False,759900.0,522107581,mdarwich12@gmail.com,2024-01-05,815000.0,...,NaN,NaN,NaN,True,True,2024-01-01,NaN,NaN,NaN,NaN
9,NaN,False,NaN,NaN,False,739900.0,510919001,mdarwich12@gmail.com,2024-01-05,810000.0,...,NaN,NaN,NaN,True,True,2024-01-01,NaN,NaN,NaN,NaN
28,NaN,True,NaN,NaN,False,2100000.0,1067652762,jenniferarielkennedy@gmail.com,2024-01-02,2100000.0,...,0.0,11219.0,NaN,False,False,2024-01-01,NaN,NaN,NaN,NaN
29,Tile,True,NaN,NaN,False,1950000.0,1063453216,kira@mendosir.com,2024-01-22,1950000.0,...,NaN,74487.6,NaN,False,False,2024-01-01,NaN,NaN,NaN,NaN
31,"Tile,Wood",True,NaN,NaN,NaN,NaN,1061988701,dannyduong@gmail.com,2024-01-31,2340000.0,...,NaN,8712.0,NaN,True,True,2024-01-01,NaN,NaN,NaN,NaN

## Remove Columns

### Too Many Null Values

In [9]:
# These columns have more than half of their rows missing

na_check = dataset.isnull().sum().sort_values(ascending=False)

num_rows = dataset.shape[0]
half = num_rows/2
print(half)

half_na = na_check[na_check >= half]
half_na.sort_values(ascending=False)

154867.5

AboveGradeFinishedArea          309735
FireplacesTotal                 309735
TaxYear                         309735
MiddleOrJuniorSchoolDistrict    309735
ElementarySchoolDistrict        309735
TaxAnnualAmount                 309735
CoveredSpaces                   309735
BusinessType                    309735
WaterfrontYN                    309599
BelowGradeFinishedArea          307832
BasementYN                      302276
BuilderName                     295276
LotSizeDimensions               290771
BuildingAreaTotal               290079
CoBuyerAgentFirstName           281894
OriginatingSystemName           276724
OriginatingSystemSubName        276724
BuyerAgencyCompensation         267488
BuyerAgencyCompensationType     267474
ElementarySchool                267361
MiddleOrJuniorSchool            267032
HighSchool                      254309
CoListAgentFirstName            239093
CoListAgentLastName             238886
CoListOfficeName                236729
AssociationFeeFrequency         231915
latfilled                       229136
lonfilled                       229136
SubdivisionName                 202382
dtype: int64

In [10]:
# Drop columns that have more than half of their values missing

dataset = dataset.drop(columns = half_na.index)

### Avoiding Data Leakage

In [11]:
# To avoid data leakage, any column that wouldn't be known at the listing date needs to be removed
dataset = dataset.drop(columns = ["DaysOnMarket", "BuyerOfficeName", "BuyerAgentMlsId",
                                            "BuyerAgentFirstName", "BuyerAgentLastName", "MlsStatus", "BuyerOfficeAOR",
                                            "PurchaseContractDate", "BuyerAgentAOR", "ContractStatusChangeDate"])

# Also, some columns should be deleted because they correlate too highly with ClosePrice
dataset = dataset.drop(columns = ["OriginalListPrice", "ListPrice"])

### Remove Unncessdary or Redundant Columns

In [12]:
# Drop any column related to the List Agent, since that won't help us predict housing prices

dataset = dataset.drop(columns = ["ListAgentFirstName", "ListAgentLastName", "ListAgentAOR", "ListAgentEmail", "ListAgentFullName"])

In [13]:
# Check if there's a difference between ListingKey and ListingKeyNumeric
full = dataset.shape[0]
matching = dataset["ListingKey"].eq(dataset["ListingKeyNumeric"]).sum()
print(f"Difference between ListingKey and ListingKeyNumeric: {full - matching}")

# Since there is not, remove ListingKeyNumeric for being redundant
dataset = dataset.drop(columns = ["ListingKeyNumeric"])

Difference between ListingKey and ListingKeyNumeric: 0

In [14]:
# Drop "UnparsedAddress", "StreetNumberNumeric"
# These features are strings with extremely high-cardinality. They will not be useful
dataset = dataset.drop(columns = ["UnparsedAddress", "StreetNumberNumeric"])

# Drop "MLSAreaMajor"
# This feature has many null values and serves moreso as metadata than useful information
dataset = dataset.drop(columns = ["MLSAreaMajor"])

## Remove Rows

### Remove Duplicates

In [15]:
# Rows that have the exact same ListingKey and CloseDate are duplicates. Remove these

dataset = dataset.drop_duplicates(subset=["ListingKey", "CloseDate"])

### Remove Impossibilities

In [16]:
# Remove rows with no ClosePrice or a ClosePrice <= 0

dataset = dataset[dataset["ClosePrice"] > 0]

In [17]:
# Remove rows with a ListDate that comes after a CloseDate
# Note that using the ~ ("not" indicator) removes invalid rows but keeps null values

dataset = dataset[~(dataset["CloseDate"] < dataset["ListingContractDate"])]

# We should now drop ListingContractDate, since it contains leakage
dataset = dataset.drop(columns = ["ListingContractDate"])

In [18]:
# Remove rows with impossible size dimensions

dataset = dataset[~(dataset["LivingArea"] <= 0)]
dataset = dataset[~(dataset["LotSizeSquareFeet"] <= 0)]
dataset = dataset[~(dataset["LotSizeArea"] <= 0)]

In [20]:
# Remove properties with a very small living space but more than 1 bedroom or 1 bathroom
# It should be possible to have a LivingArea this small and have more than 2 bedrooms/bathrooms

dataset = dataset[~((dataset["LivingArea"] <= 200) & (dataset["BathroomsTotalInteger"] > 1))]
dataset = dataset[~((dataset["LivingArea"] <= 200) & (dataset["BedroomsTotal"] > 1))]

In [21]:
# California latitudes are postive, while longitudes are negative
# Remove all rows that don't fit this pattern

dataset = dataset[~(dataset["Latitude"] <= 0)]
dataset = dataset[~(dataset["Longitude"] >= 0)]

## Train/Test Split

In [26]:
# In order to avoid leakage, all data imputation, encoding, and outlier removal must be based only
# on the training set, then applied to the test set.

# The test set will always be the most recent month.
# The training set months can be changed at will.

# Test Set: April 2026.
# Current Training Set: January 2024 - March 2026

test_set = dataset[dataset["PropertyMonth"] == "2024-04-01"]
train_set = dataset[~(dataset["PropertyMonth"] == "2024-04-01")]

## Handle Outliers

In [28]:
# Outlier cutoffs need to be learned only on the training dataset to avoid data leakage.
# Then, those cutoffs can be applied to the testing set

### Remove ClosePrice Outliers

In [29]:
def cut_outliers(df, col, lower, upper):
    df = df[df[col] >= lower]
    df = df[df[col] <= upper]
    return df

In [30]:
# Get the 0.05 and 0.95 percentile values on the training ClosePrice.
# Using these cutoffs, remove any values outside of these percentiles from both the training and test sets

lower = train_set["ClosePrice"].quantile(0.05)
upper = train_set["ClosePrice"].quantile(0.95)

train_set = cut_outliers(train_set, "ClosePrice", lower, upper)
test_set = cut_outliers(test_set, "ClosePrice", lower, upper)

### Winsorize Small Numeric Outliers

In [31]:
# Columns to winsorize: “ParkingTotal”, “BathroomsTotalInteger”, “BedroomsTotal”, “MainLevelBedrooms”, “GarageSpaces”, “Stories”
# Once again, calculate the cutoffs on the training set, and apply those same cutoffs to the test set

upper_bound = train_set["ParkingTotal"].quantile(0.95)
train_set["ParkingTotal"] = train_set["ParkingTotal"].clip(lower=0, upper=upper_bound)
test_set["ParkingTotal"] = test_set["ParkingTotal"].clip(lower=0, upper=upper_bound)

upper_bound = train_set["BathroomsTotalInteger"].quantile(0.95)
train_set["BathroomsTotalInteger"] = train_set["BathroomsTotalInteger"].clip(lower=0, upper=upper_bound)
test_set["BathroomsTotalInteger"] = test_set["BathroomsTotalInteger"].clip(lower=0, upper=upper_bound)

upper_bound = train_set["BedroomsTotal"].quantile(0.95)
train_set["BedroomsTotal"] = train_set["BedroomsTotal"].clip(lower=0, upper=upper_bound)
test_set["BedroomsTotal"] = test_set["BedroomsTotal"].clip(lower=0, upper=upper_bound)

upper_bound = train_set["MainLevelBedrooms"].quantile(0.95)
train_set["MainLevelBedrooms"] = train_set["MainLevelBedrooms"].clip(lower=0, upper=upper_bound)
test_set["MainLevelBedrooms"] = test_set["MainLevelBedrooms"].clip(lower=0, upper=upper_bound)

upper_bound = train_set["GarageSpaces"].quantile(0.95)
train_set["GarageSpaces"] = train_set["GarageSpaces"].clip(lower=0, upper=upper_bound)
test_set["GarageSpaces"] = test_set["GarageSpaces"].clip(lower=0, upper=upper_bound)

upper_bound = train_set["Stories"].quantile(0.95)
train_set["Stories"] = train_set["Stories"].clip(lower=0, upper=upper_bound)
test_set["Stories"] = test_set["Stories"].clip(lower=0, upper=upper_bound)

## Handle Missing Values

In [37]:
train_set.isna().sum().sort_values(ascending=False)

MainLevelBedrooms        106897
Flooring                  94970
AssociationFee            79610
HighSchoolDistrict        70104
Stories                   31086
AttachedGarageYN          27826
ViewYN                    25464
Levels                    23413
PoolPrivateYN             22847
NewConstructionYN         20296
GarageSpaces               8985
LotSizeAcres               4826
LotSizeSquareFeet          4818
LotSizeArea                4800
Longitude                  2449
Latitude                   2449
ParkingTotal                337
City                        175
FireplaceYN                 152
YearBuilt                   103
LivingArea                   70
BathroomsTotalInteger        40
PostalCode                    1
StateOrProvince               0
BedroomsTotal                 0
ListingId                     0
CountyOrParish                0
ListOfficeName                0
ClosePrice                    0
CloseDate                     0
ListingKey                    0
PropertyMonth                 0
dtype: int64

### Property Features (Categorical)

In [38]:
# Fill null boolean values with "Unknown"

train_set["AttachedGarageYN"] = train_set["AttachedGarageYN"].fillna("Unknown").infer_objects(copy=False)
train_set["PoolPrivateYN"] = train_set["PoolPrivateYN"].fillna("Unknown").infer_objects(copy=False)
train_set["ViewYN"] = train_set["ViewYN"].fillna("Unknown").infer_objects(copy=False)
train_set["NewConstructionYN"] = train_set["NewConstructionYN"].fillna("Unknown").infer_objects(copy=False)
train_set["FireplaceYN"] = train_set["FireplaceYN"].fillna("Unknown").infer_objects(copy=False)

test_set["AttachedGarageYN"] = test_set["AttachedGarageYN"].fillna("Unknown").infer_objects(copy=False)
test_set["PoolPrivateYN"] = test_set["PoolPrivateYN"].fillna("Unknown").infer_objects(copy=False)
test_set["ViewYN"] = test_set["ViewYN"].fillna("Unknown").infer_objects(copy=False)
test_set["NewConstructionYN"] = test_set["NewConstructionYN"].fillna("Unknown").infer_objects(copy=False)
test_set["FireplaceYN"] = test_set["FireplaceYN"].fillna("Unknown").infer_objects(copy=False)

In [39]:
# Fill null Flooring values with "Unknown"

train_set["Flooring"] = train_set["Flooring"].fillna("Unknown")
test_set["Flooring"] = test_set["Flooring"].fillna("Unknown")

### Property Features (Small Numerical)

#### Stories vs. Levels

In [41]:
# Stories and Levels seem to encode similar data. Check the difference

print(train_set["Levels"].value_counts())
print("-----")
print(train_set["Stories"].value_counts())

Levels
One                               151218
Two                                82967
ThreeOrMore                         4261
MultiSplit                          3474
One,Two                              521
Two,MultiSplit                       376
Two,One                              251
One,MultiSplit                       140
ThreeOrMore,MultiSplit               139
Two,ThreeOrMore                       82
One,ThreeOrMore                       40
MultiSplit,One                        23
One,Two,MultiSplit                     9
Two,ThreeOrMore,MultiSplit             5
One,Two,ThreeOrMore                    5
ThreeOrMore,One                        5
One,Two,ThreeOrMore,MultiSplit         3
Name: count, dtype: int64
-----
Stories
1.0    152593
2.0     83253
Name: count, dtype: int64

In [42]:
# For all the null values in Stories, how are these rows represented in Levels?

train_set[train_set["Stories"].isna() == True]["Levels"].value_counts(dropna=False)

Levels
NaN                       23224
ThreeOrMore                4260
MultiSplit                 3463
ThreeOrMore,MultiSplit      139
Name: count, dtype: int64

In [43]:
# Impute Stories by referencing Levels
# ThreeOrMore in Levels -> 3.0 in Stories
# Multisplit in Levels -> 1.5 in Stories
# hreeOrMore,MultiSplit in Levels -> 3.5 in Stories

train_set.loc[(train_set["Stories"].isna()) & (train_set["Levels"] == "ThreeOrMore"), "Stories"] = 3.0
train_set.loc[(train_set["Stories"].isna()) & (train_set["Levels"] == "MultiSplit"), "Stories"] = 1.5
train_set.loc[(train_set["Stories"].isna()) & (train_set["Levels"] == "ThreeOrMore,MultiSplit"), "Stories"]= 3.5

test_set.loc[(test_set["Stories"].isna()) & (test_set["Levels"] == "ThreeOrMore"), "Stories"] = 3.0
test_set.loc[(test_set["Stories"].isna()) & (test_set["Levels"] == "MultiSplit"), "Stories"] = 1.5
test_set.loc[(test_set["Stories"].isna()) & (test_set["Levels"] == "ThreeOrMore,MultiSplit"), "Stories"]= 3.5

In [44]:
# There are still missing values of Stories to handle

train_set["Stories"].value_counts(dropna=False)

Stories
1.0    152593
2.0     83253
NaN     23224
3.0      4260
1.5      3463
3.5       139
Name: count, dtype: int64

In [45]:
# Calculate the median of LivingArea for each amount of stories
# Reminder: cutoffs like this are computed only on train_set!

one_story_median = train_set[train_set["Stories"] == 1.0 ]["LivingArea"].median()
one_half_story_median = train_set[train_set["Stories"] == 1.5 ]["LivingArea"].median()
two_story_median = train_set[train_set["Stories"] == 2.0 ]["LivingArea"].median()
three_story_median = train_set[train_set["Stories"] == 3.0 ]["LivingArea"].median()
three_half_story_median = train_set[train_set["Stories"] == 3.5 ]["LivingArea"].median()

print(one_story_median, one_half_story_median, two_story_median, three_story_median, three_half_story_median)

1560.0 2146.0 2335.0 2368.0 2419.0

In [46]:
# Create ranges betwen each LivingArea median

midpoint_1 = (one_story_median + one_half_story_median) / 2
midpoint_2 = (one_half_story_median + two_story_median) / 2
midpoint_3 = (two_story_median + three_story_median) / 2
midpoint_4 = (three_story_median + three_half_story_median) / 2 

# [-, midpoint_1) = 1 story
# [midpoint_1, midpoint_2) = 1.5 stories
# [midpoint_2, midpoint_3) = 2 stories
# [midpoint_3, minpoint_4) = 3 stories
# [midpoint_4, +] = 3.5 stories

In [47]:
# Use the ranges of LivingArea to impute how many stories that amount of LivingArea is likely to correspond to

train_set.loc[(train_set["Stories"].isna()) & 
                (train_set["LivingArea"] < midpoint_1),
                "Stories"] = 1.0
test_set.loc[(test_set["Stories"].isna()) & 
            (test_set["LivingArea"] < midpoint_1),
            "Stories"] = 1.0

train_set.loc[(train_set["Stories"].isna()) & 
            (train_set["LivingArea"] >= midpoint_1) &
            (train_set["LivingArea"] < midpoint_2),
            "Stories"] = 1.5
test_set.loc[(test_set["Stories"].isna()) & 
            (test_set["LivingArea"] >= midpoint_1) &
            (test_set["LivingArea"] < midpoint_2),
            "Stories"] = 1.5

train_set.loc[(train_set["Stories"].isna()) & 
            (train_set["LivingArea"] >= midpoint_2) &
            (train_set["LivingArea"] < midpoint_3),
            "Stories"]= 2.0
test_set.loc[(test_set["Stories"].isna()) & 
            (test_set["LivingArea"] >= midpoint_2) &
            (test_set["LivingArea"] < midpoint_3),
            "Stories"]= 2.0

train_set.loc[(train_set["Stories"].isna()) & 
            (train_set["LivingArea"] >= midpoint_3) &
            (train_set["LivingArea"] < midpoint_4),
            "Stories"] = 3.0
test_set.loc[(test_set["Stories"].isna()) & 
            (test_set["LivingArea"] >= midpoint_3) &
            (test_set["LivingArea"] < midpoint_4),
            "Stories"] = 3.0

train_set.loc[(train_set["Stories"].isna()) & 
            (train_set["LivingArea"] >= midpoint_4),
            "Stories"] = 3.5
test_set.loc[(test_set["Stories"].isna()) & 
            (test_set["LivingArea"] >= midpoint_4),
            "Stories"] = 3.5

In [48]:
# Drop Levels, since its information is now encoded in Stories

train_set = train_set.drop(columns = ["Levels"])
test_set = test_set.drop(columns = ["Levels"])

#### Bathrooms

In [49]:
# Get the median of bathrooms from each story

one_story_bath = train_set[train_set["Stories"] == 1.0 ]["BathroomsTotalInteger"].median()
one_half_story_bath = train_set[train_set["Stories"] == 1.5 ]["BathroomsTotalInteger"].median()
two_story_bath = train_set[train_set["Stories"] == 2.0 ]["BathroomsTotalInteger"].median()
three_story_bath = train_set[train_set["Stories"] == 3.0 ]["BathroomsTotalInteger"].median()
three_half_story_bath = train_set[train_set["Stories"] == 3.5 ]["BathroomsTotalInteger"].median()

print(one_story_bath, one_half_story_bath, two_story_bath, three_story_bath, three_half_story_bath)

2.0 3.0 3.0 3.0 3.0

In [50]:
# Impute BathroomsTotalInteger with median bathrooms of each story

train_set.loc[(train_set["BathroomsTotalInteger"].isna()) &
            (train_set["Stories"] == 1.0),
            "BathroomsTotalInteger"] = one_story_bath
test_set.loc[(test_set["BathroomsTotalInteger"].isna()) &
            (test_set["Stories"] == 1.0),
            "BathroomsTotalInteger"] = one_story_bath

train_set.loc[(train_set["BathroomsTotalInteger"].isna()) &
            (train_set["Stories"] == 1.5),
            "BathroomsTotalInteger"] = one_half_story_bath
test_set.loc[(test_set["BathroomsTotalInteger"].isna()) &
            (test_set["Stories"] == 1.5),
            "BathroomsTotalInteger"] = one_half_story_bath

train_set.loc[(train_set["BathroomsTotalInteger"].isna()) &
            (train_set["Stories"] == 2.0),
            "BathroomsTotalInteger"] = two_story_bath
test_set.loc[(test_set["BathroomsTotalInteger"].isna()) &
            (test_set["Stories"] == 2.0),
            "BathroomsTotalInteger"] = two_story_bath

train_set.loc[(train_set["BathroomsTotalInteger"].isna()) &
            (train_set["Stories"] == 3.0),
            "BathroomsTotalInteger"] = three_story_bath
test_set.loc[(test_set["BathroomsTotalInteger"].isna()) &
            (test_set["Stories"] == 3.0),
            "BathroomsTotalInteger"] = three_story_bath

train_set.loc[(train_set["BathroomsTotalInteger"].isna()) &
            (train_set["Stories"] == 3.5),
            "BathroomsTotalInteger"] = three_half_story_bath
test_set.loc[(test_set["BathroomsTotalInteger"].isna()) &
            (test_set["Stories"] == 3.5),
            "BathroomsTotalInteger"] = three_half_story_bath

#### Bedrooms

In [51]:
# If the property only has one story, fill MainLevelBedrooms with the same number as BedroomsTotal

train_set["MainLevelBedrooms"] = np.where((train_set["Stories"] == 1.0) &
                                            train_set["MainLevelBedrooms"].isna() == True,
                                            train_set["BedroomsTotal"], train_set["MainLevelBedrooms"])
test_set["MainLevelBedrooms"] = np.where((test_set["Stories"] == 1.0) &
                                            test_set["MainLevelBedrooms"].isna() == True,
                                            test_set["BedroomsTotal"], test_set["MainLevelBedrooms"])

# Otherwise, impute with the median of non one story properties
plus_one_story_bed_median = train_set[train_set["Stories"] > 1.0]["MainLevelBedrooms"].median()

train_set["MainLevelBedrooms"] = train_set["MainLevelBedrooms"].fillna(plus_one_story_bed_median)
test_set["MainLevelBedrooms"] = test_set["MainLevelBedrooms"].fillna(plus_one_story_bed_median)

#### Parking

In [52]:
# For all the ParkingTotal spaces that are null, the GarageSpaces column has values

train_set[train_set["ParkingTotal"].isna() == True]["GarageSpaces"].value_counts(dropna=False)

GarageSpaces
2.0    225
1.0     43
0.0     35
3.0     34
Name: count, dtype: int64

In [53]:
# Impute missing ParkingTotal values with GarageSpaces

train_set["ParkingTotal"] = train_set["ParkingTotal"].fillna(train_set["GarageSpaces"])
test_set["ParkingTotal"] = test_set["ParkingTotal"].fillna(test_set["GarageSpaces"])

#### GarageSpaces

In [54]:
# Impute values for GarageSpaces by using AttachedGarageYN.
# AttachedGarageYN = false does not necessarily mean no garage exists, just that it's not attached.

# Take median GarageSpaces for each value of AttachedGarageYN
garage_t = train_set[train_set["AttachedGarageYN"] == True]["GarageSpaces"].median()
garage_f = train_set[train_set["AttachedGarageYN"] == False]["GarageSpaces"].median()
garage_u = train_set[train_set["AttachedGarageYN"] == "Unknown"]["GarageSpaces"].median()

# Impute GarageSpaces with the medians created using AttachedGarageYN
train_set.loc[(train_set["GarageSpaces"].isna()) & (train_set["AttachedGarageYN"] == True), "GarageSpaces"] = 2.0
train_set.loc[(train_set["GarageSpaces"].isna()) & (train_set["AttachedGarageYN"] == False), "GarageSpaces"] = 2.0
train_set.loc[(train_set["GarageSpaces"].isna()) & (train_set["AttachedGarageYN"] == "Unknown"), "GarageSpaces"]= 0.0

test_set.loc[(test_set["GarageSpaces"].isna()) & (test_set["AttachedGarageYN"] == True), "GarageSpaces"] = 2.0
test_set.loc[(test_set["GarageSpaces"].isna()) & (test_set["AttachedGarageYN"] == False), "GarageSpaces"] = 2.0
test_set.loc[(test_set["GarageSpaces"].isna()) & (test_set["AttachedGarageYN"] == "Unknown"), "GarageSpaces"]= 0.0

### Property Features (Large Numerical)

#### LotSize Units

In [56]:
# Check differences in units

### Notes
# LotSizeArea uses ambigious units, seemingly a combination of LotSizeAcres or LotSizeSquareFeet. Not ideal to use.
# Between LotSizeAcres and LotSizeSquareFeet, LotSizeSquareFeet appears better since its values are more precise

dataset[["LotSizeAcres", "LotSizeArea", "LotSizeSquareFeet"]]

       LotSizeAcres  LotSizeArea  LotSizeSquareFeet
5               NaN          NaN                NaN
9               NaN          NaN                NaN
28           0.2576     11219.00            11219.0
29           1.7100         1.71            74487.6
31           0.2000      8712.00             8712.0
...             ...          ...                ...
24227        0.1830      7971.00             7971.0
24228        0.1194      5200.00             5200.0
24229        0.2300     10019.00            10019.0
24231        0.2777     12096.00            12096.0
24234       19.7400        19.74           859874.4

[309317 rows x 3 columns]

In [57]:
# Since LotSizeSquareFeet is the best LotSize column, investigate if other features can be used to fill its null values

dataset[(dataset["LotSizeSquareFeet"].isna() == True) &
        (dataset["LotSizeAcres"].isna() == False) &
        (dataset["LotSizeArea"].isna() == False)][["LotSizeAcres", "LotSizeArea"]].head(10)

# Where LotSizeSquareFeet is null and the other values exist, both values seem to be in square feet

       LotSizeAcres  LotSizeArea
12995    57092.0000   57092.0000
6915     64013.0000   64013.0000
11962    86248.0000   86248.0000
14829    87991.0000   87991.0000
17828   571837.0000  571837.0000
19452    81282.0000   81282.0000
12973    67790.1556   67790.1556
20535    54450.0000   54450.0000
8769     63598.0000   63598.0000
18378    68393.0000   68393.0000

In [58]:
# Fill missing LotSizeSquareFeet values with LotSizeArea

train_set["LotSizeSquareFeet"] = train_set["LotSizeSquareFeet"].fillna(train_set["LotSizeArea"])
test_set["LotSizeSquareFeet"] = test_set["LotSizeSquareFeet"].fillna(test_set["LotSizeArea"])

In [59]:
# Having multiple LotSize columns in redundant. Keep LotSizeSquareFeet and drop LotSizeAcres and LotSizeArea

train_set = train_set.drop(columns = ["LotSizeAcres", "LotSizeArea"])
test_set = test_set.drop(columns = ["LotSizeAcres", "LotSizeArea"])

#### LotSizeSquareFeet and LivingArea

In [60]:
# Calculate the median LivingArea and LotSizeSquareFeet for each number of stories

one_story_living = train_set[train_set["Stories"] == 1.0]["LivingArea"].median()
one_story_feet = train_set[train_set["Stories"] == 1.0]["LotSizeSquareFeet"].median()

half_story_living = train_set[train_set["Stories"] == 1.5]["LivingArea"].median()
half_story_feet = train_set[train_set["Stories"] == 1.5]["LotSizeSquareFeet"].median()

two_story_living = train_set[train_set["Stories"] == 2.0]["LivingArea"].median()
two_story_feet = train_set[train_set["Stories"] == 2.0]["LotSizeSquareFeet"].median()

three_story_living = train_set[train_set["Stories"] == 3.0]["LivingArea"].median()
three_story_feet = train_set[train_set["Stories"] == 3.0]["LotSizeSquareFeet"].median()

three_half_story_living = train_set[train_set["Stories"] == 3.5]["LivingArea"].median()
three_half_story_feet = train_set[train_set["Stories"] == 3.5]["LotSizeSquareFeet"].median()

In [61]:
# For each number of stories, fill LivingArea with the median value found previously

train_set.loc[(train_set["LivingArea"].isna()) & 
            (train_set["Stories"] == 1.0),
            "LivingArea"] = one_story_living
test_set.loc[(test_set["LivingArea"].isna()) & 
            (test_set["Stories"] == 1.0),
            "LivingArea"] = one_story_living

train_set.loc[(train_set["LivingArea"].isna()) & 
            (train_set["Stories"] == 1.5),
            "LivingArea"] = half_story_living
test_set.loc[(test_set["LivingArea"].isna()) & 
            (test_set["Stories"] == 1.5),
            "LivingArea"] = half_story_living

train_set.loc[(train_set["LivingArea"].isna()) & 
            (train_set["Stories"] == 2.0),
            "LivingArea"] = two_story_living
test_set.loc[(test_set["LivingArea"].isna()) & 
            (test_set["Stories"] == 2.0),
            "LivingArea"] = two_story_living

train_set.loc[(train_set["LivingArea"].isna()) & 
            (train_set["Stories"] == 3.0),
            "LivingArea"] = three_story_living
test_set.loc[(test_set["LivingArea"].isna()) & 
            (test_set["Stories"] == 3.0),
            "LivingArea"] = three_story_living

train_set.loc[(train_set["LivingArea"].isna()) & 
             (train_set["Stories"] == 3.5),
            "LivingArea"] = three_half_story_living
test_set.loc[(test_set["LivingArea"].isna()) & 
             (test_set["Stories"] == 3.5),
            "LivingArea"] = three_half_story_living

In [62]:
# For each number of stories, fill LivingArea with the median value found previously

train_set.loc[(train_set["LotSizeSquareFeet"].isna()) & 
            (train_set["Stories"] == 1.0),
            "LotSizeSquareFeet"] = one_story_feet
test_set.loc[(test_set["LotSizeSquareFeet"].isna()) & 
            (test_set["Stories"] == 1.0),
            "LotSizeSquareFeet"] = one_story_feet

train_set.loc[(train_set["LotSizeSquareFeet"].isna()) & 
            (train_set["Stories"] == 1.5),
            "LotSizeSquareFeet"] = half_story_feet
test_set.loc[(test_set["LotSizeSquareFeet"].isna()) & 
            (test_set["Stories"] == 1.5),
            "LotSizeSquareFeet"] = half_story_feet

train_set.loc[(train_set["LotSizeSquareFeet"].isna()) & 
            (train_set["Stories"] == 2.0),
            "LotSizeSquareFeet"] = two_story_feet
test_set.loc[(test_set["LotSizeSquareFeet"].isna()) & 
            (test_set["Stories"] == 2.0),
            "LotSizeSquareFeet"] = two_story_feet

train_set.loc[(train_set["LotSizeSquareFeet"].isna()) & 
            (train_set["Stories"] == 3.0),
            "LotSizeSquareFeet"] = three_story_feet
test_set.loc[(test_set["LotSizeSquareFeet"].isna()) & 
            (test_set["Stories"] == 3.0),
            "LotSizeSquareFeet"] = three_story_feet

train_set.loc[(train_set["LotSizeSquareFeet"].isna()) & 
            (train_set["Stories"] == 3.5),
            "LotSizeSquareFeet"] = three_half_story_feet
test_set.loc[(test_set["LotSizeSquareFeet"].isna()) & 
            (test_set["Stories"] == 3.5),
            "LotSizeSquareFeet"] = three_half_story_feet

#### AssociationFee

In [63]:
# Fill AssocationFee with median value

median_fee = train_set["AssociationFee"].median()

train_set["AssociationFee"] = train_set["AssociationFee"].fillna(median_fee)
test_set["AssociationFee"] = test_set["AssociationFee"].fillna(median_fee)

### Location Features

#### HighSchoolDistrict

In [65]:
# Keep HighSchoolDistrict for potential feature engineering later
# Fill its null values with unknown

train_set["HighSchoolDistrict"] = train_set["HighSchoolDistrict"].fillna("Unknown")
test_set["HighSchoolDistrict"] = test_set["HighSchoolDistrict"].fillna("Unknown")

#### Longitude and Latitude

In [66]:
!pip install uszipcode -q

In [67]:
pip install --upgrade uszipcode -q

Note: you may need to restart the kernel to use updated packages.

In [68]:
# import uszipcode database (above pip installs are necessary for using it)
# website: https://pypi.org/project/uszipcode/
# Has information on zipcodes
# Based on 2020 census data, however it's not out of date, since I'm only using the locational, not demographic data

from uszipcode import SearchEngine
search = SearchEngine()

/opt/anaconda3/lib/python3.13/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [69]:
# Longitude and Latitude are either both filled or both null

dataset[["Longitude", "Latitude"]].isnull().value_counts()

Longitude  Latitude
False      False       306609
True       True          2708
Name: count, dtype: int64

In [70]:
# There is one missing PostalCode value, drop this

print(train_set["PostalCode"].isna().sum())
print(test_set["PostalCode"].isna().sum())

train_set = train_set.dropna(subset=["PostalCode"])
test_set = test_set.dropna(subset=["PostalCode"])

1
0

In [71]:
# Get the PostalCode from every row where longitude and latitude are missing

zipcodes_train = train_set[train_set["Longitude"].isna() == True][["PostalCode"]].values.flatten().tolist()
zipcodes_test = test_set[test_set["Longitude"].isna() == True][["PostalCode"]].values.flatten().tolist()

# Run each PostalCode through uszipcodes's search. Save the longitude and latitude of each PostalCode
# Also save PostalCodes that uszipcode marks as invalid

invalid_train = []
lat_dict_train = {}
long_dict_train = {}

for i in zipcodes_train:
    result_train = search.by_zipcode(i)
    if result_train is None:
        invalid_train.append(i)
    if result_train is not None:
        lat_dict_train[i] = result_train.lat
        long_dict_train[i] = result_train.lng

invalid_test = []
lat_dict_test = {}
long_dict_test = {}

for i in zipcodes_test:
    result_test = search.by_zipcode(i)
    if result_test is None:
        invalid_test.append(i)
    if result_test is not None:
        lat_dict_test[i] = result_test.lat
        long_dict_test[i] = result_test.lng

In [72]:
# Check which PostalCodes were marked as invalid

print(invalid_train) # invalid zipcodes are those that are ranges
print(invalid_test) # no invalid zipcodes

['94804-1101', '94560-1710', '94582-5069', '95337-6695', '94611-3402', '94710-2809', '94519-1610', '94609-1626', '94605-3813', '94587-4913', '94588-3111', '94587-4748', '94501-0000', '94506-6020', '95336-5956', '95386-9479', '94044-4140', '94549-2925', '94509-6864', '94603-4111', '94536-4263', '95386-9551', '91748-3992', '94530-2567', '94568-4697', '94561-9999', '94509-5639', '94520-1605', '94803-3627', '94513-4478', '94804-4303', '94509-5966', '94513-5168', '94513-4255', '94506-4637', '94513-6479', '94536-5026', '94601-5102', '95330-8896', '95240-0000', '95330-0000', '94603-2034', '94624-3118', '94505-9480', '94506-1918', '94561-0000', '94601-3843', '94509-8923', '95758-7921', '94531-9317', '95330-0000', '94806-2168', '95125-1529', '94512-4814', '49603', '94541-7165', '94566-2931', '94607-2928', '94578-1907', '94555-3', '94705-1628']
[]

In [73]:
# Remove the rows that have a range of zipcodes

pattern = r'-'
train_set = train_set[~train_set["PostalCode"].str.contains(pattern, na=False, regex=True)]
test_set = test_set[~test_set["PostalCode"].str.contains(pattern, na=False, regex=True)]

In [74]:
# There is one more invalid zipcode, 49603

print(train_set[train_set["PostalCode"] == "49603"]["City"]) # City = Oakland

# Searching this zipcode in the data shows that the city is Oakland
# Since Oakland's real zipcode is 94603, this appears to be a data entry error
# Change the invalid zipcode to the correct one

train_set["PostalCode"] = train_set["PostalCode"].replace("49603", "94603")

3951    Oakland
Name: City, dtype: object

In [75]:
# Fill the null values with the imputed values from uszipcode

train_set["Longitude"] = train_set["Longitude"].fillna(train_set["PostalCode"].map(long_dict_train))
train_set["Latitude"] = train_set["Latitude"].fillna(train_set["PostalCode"].map(lat_dict_train))

test_set["Longitude"] = test_set["Longitude"].fillna(test_set["PostalCode"].map(long_dict_test))
test_set["Latitude"] = test_set["Latitude"].fillna(test_set["PostalCode"].map(lat_dict_test))

#### City

In [76]:
# Get the PostalCode from every row where city is missing

zipcodes_train = train_set[train_set["City"].isna() == True][["PostalCode"]].values.flatten().tolist()
zipcodes_test = test_set[test_set["City"].isna() == True][["PostalCode"]].values.flatten().tolist()

# Run each PostalCode through uszipcodes's search. Save the longitude and latitude of each PostalCode
# Also save PostalCodes that uszipcode marks as invalid

invalid_train = []
city_train = {}

for i in zipcodes_train:
    result_train = search.by_zipcode(i)
    if result_train is None:
        invalid_train.append(i)
    if result_train is not None:
        city_train[i] = result_train.city

invalid_test = []
city_test = {}

for i in zipcodes_test:
    result_test = search.by_zipcode(i)
    if result_test is None:
        invalid_test.append(i)
    if result_test is not None:
        city_test[i] = result_test.city

In [77]:
# Check which PostalCodes were marked as invalid

print(invalid_train) # 92440 is invalid
print(invalid_test) # no invalid zipcodes

['92440', '92440']
[]

In [78]:
# Investigate invalid 92440 zipcode

train_set[train_set["PostalCode"] == "92440"][["PostalCode", "Longitude", "Latitude", "City"]].head(8)

# It seems that PostalCode = 92240 should correspond to "Desert Hot Springs"
# However 92240 is not a valid California zipcode.
# Searching up the zipcode of Dessert Hot Springs on Google shows that its zipcode is 92240
# Thus, 92440 is a data entry error and these values should actually be 92240!

      PostalCode   Longitude   Latitude                City
19419      92440 -116.567859  33.968449  Desert Hot Springs
20731      92440 -116.566796  33.968075  Desert Hot Springs
20733      92440 -116.566850  33.968494  Desert Hot Springs
14116      92440 -116.565670  33.968423  Desert Hot Springs
13461      92440 -116.565670  33.968423  Desert Hot Springs
16179      92440 -116.565026  33.968733  Desert Hot Springs
17110      92440 -116.566324  33.968378  Desert Hot Springs
4453       92440 -116.564908  33.967852                 NaN

In [79]:
# Fill the missing 92440 cities with "Desert Hot Springs"
train_set.loc[(train_set["City"].isna()) & (train_set["PostalCode"] == "92440"), "City"] = "Desert Hot Springs"

# Then change all 92440 PostalCode to the correct value 92240
train_set["PostalCode"] = train_set["PostalCode"].replace("92440", "92240")

In [80]:
# Impute the remaining null city values with the PostalCode-City dictionary

train_set["City"] = train_set["City"].fillna(train_set["PostalCode"].map(city_train))
test_set["City"] = test_set["City"].fillna(test_set["PostalCode"].map(city_test))

### YearBuilt

In [81]:
# Impute YearBuilt with the median YearBuilt from each city

cities_train = train_set["City"].unique()
cities_test = test_set["City"].unique()

city_year_dict_train = {}
for city in cities_train:
    city_year_dict_train[city] = train_set[train_set["City"] == city]["YearBuilt"].median()

city_year_dict_test = {}
for city in cities_test:
    city_year_dict_test[city] = test_set[test_set["City"] == city]["YearBuilt"].median()

In [82]:
# Use the dictionary of City-YearBuilt to fill missing YearBuilt values

train_set["YearBuilt"] = train_set["YearBuilt"].fillna(train_set["City"].map(city_year_dict_train))
test_set["YearBuilt"] = test_set["YearBuilt"].fillna(test_set["City"].map(city_year_dict_test))

## Scaling

### Log Transform Large Numeric Features

In [86]:
# Columns to apply a log to: “ClosePrice”, “LivingArea”, “LotSizeSquareFeet”, “AssociationFee”
# These values have an extreme right skew, which applying a log transformation can help with

train_set["ClosePriceLog"] = np.log(train_set["ClosePrice"])
test_set["ClosePriceLog"] = np.log(test_set["ClosePrice"])

train_set["LivingAreaLog"] = np.log(train_set["LivingArea"])
test_set["LivingAreaLog"] = np.log(test_set["LivingArea"])

train_set["LotSizeSquareFeetLog"] = np.log(train_set["LotSizeSquareFeet"])
test_set["LotSizeSquareFeetLog"] = np.log(test_set["LotSizeSquareFeet"])

# Make sure AssociationFee is non-negative
train_set = train_set[train_set["AssociationFee"] >= 0]
train_set["AssociationFeeLog"] = np.log(train_set["AssociationFee"] + 1)
test_set = test_set[test_set["AssociationFee"] >= 0]
test_set["AssociationFeeLog"] = np.log(test_set["AssociationFee"] + 1)

## Encode Categorical Features

### Low Cardinality Features

#### Booleans

In [88]:
# Change Booleans to 0 = False, 1 = True, 0.5 = "Unknown"
pd.set_option("future.no_silent_downcasting", True) # stops error message

train_set["ViewYN"] = train_set["ViewYN"].replace({False: 0, True: 1, "Unknown": 0.5})
train_set["PoolPrivateYN"] = train_set["PoolPrivateYN"].replace({False: 0, True: 1, "Unknown": 0.5})
train_set["AttachedGarageYN"] = train_set["AttachedGarageYN"].replace({False: 0, True: 1, "Unknown": 0.5})
train_set["FireplaceYN"] = train_set["FireplaceYN"].replace({False: 0, True: 1, "Unknown": 0.5})
train_set["NewConstructionYN"] = train_set["NewConstructionYN"].replace({False: 0, True: 1, "Unknown": 0.5})

test_set["ViewYN"] = test_set["ViewYN"].replace({False: 0, True: 1, "Unknown": 0.5})
test_set["PoolPrivateYN"] = test_set["PoolPrivateYN"].replace({False: 0, True: 1, "Unknown": 0.5})
test_set["AttachedGarageYN"] = test_set["AttachedGarageYN"].replace({False: 0, True: 1, "Unknown": 0.5})
test_set["FireplaceYN"] = test_set["FireplaceYN"].replace({False: 0, True: 1, "Unknown": 0.5})
test_set["NewConstructionYN"] = test_set["NewConstructionYN"].replace({False: 0, True: 1, "Unknown": 0.5})

#### Flooring

In [89]:
# Split the flooring values into a list

floors_train = train_set["Flooring"].str.split(",")
floors_test = test_set["Flooring"].str.split(",")

floors_train

5                    [Unknown]
9                    [Unknown]
28                   [Unknown]
29                      [Tile]
31                [Tile, Wood]
                 ...
24226                 [Carpet]
24227    [Carpet, Tile, Vinyl]
24228                [Unknown]
24231     [Carpet, Tile, Wood]
24234                  [Vinyl]
Name: Flooring, Length: 265350, dtype: object

In [90]:
# One hot encode the the flooring list

mlb = MultiLabelBinarizer()
floors_ohe_train = pd.DataFrame(mlb.fit_transform(floors_train), columns=mlb.classes_, index=train_set.index)

mlb = MultiLabelBinarizer()
floors_ohe_test = pd.DataFrame(mlb.fit_transform(floors_test), columns=mlb.classes_, index=test_set.index)

# Add ListingKey and CloseDate to this new dataframe in order to match it back to orignial dataframe
floors_ohe_train["ListingKey"] = train_set["ListingKey"]
floors_ohe_train["CloseDate"] = train_set["CloseDate"]

floors_ohe_test["ListingKey"] = test_set["ListingKey"]
floors_ohe_test["CloseDate"] = test_set["CloseDate"]

floors_ohe_train

,Bamboo,Brick,Carpet,Concrete,Laminate,SeeRemarks,Stone,Tile,Unknown,Vinyl,Wood,ListingKey,CloseDate
5,0,0,0,0,0,0,0,0,1,0,0,522107581,2024-01-05
9,0,0,0,0,0,0,0,0,1,0,0,510919001,2024-01-05
28,0,0,0,0,0,0,0,0,1,0,0,1067652762,2024-01-02
29,0,0,0,0,0,0,0,1,0,0,0,1063453216,2024-01-22
31,0,0,0,0,0,0,0,1,0,0,1,1061988701,2024-01-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24226,0,0,1,0,0,0,0,0,0,0,0,1075789574,2026-04-30
24227,0,0,1,0,0,0,0,1,0,1,0,1073242811,2026-04-30
24228,0,0,0,0,0,0,0,0,1,0,0,1073214872,2026-04-01
24231,0,0,1,0,0,0,0,1,0,0,1,1067010583,2026-04-13
24234,0,0,0,0,0,0,0,0,0,1,0,1063196193,2026-04-16

In [91]:
# Merge the one-hot-encoded flooring columns back to original dataset

train_set = pd.merge(train_set, floors_ohe_train, on=["ListingKey", "CloseDate"]).drop(columns=["CloseDate", "Flooring"])
test_set = pd.merge(test_set, floors_ohe_test, on=["ListingKey", "CloseDate"]).drop(columns=["CloseDate", "Flooring"])

#### StateOrProvince

In [92]:
# One hot encode the state feaure

train_set = pd.get_dummies(train_set, columns=["StateOrProvince"], dtype=int)
test_set = pd.get_dummies(test_set, columns=["StateOrProvince"], dtype=int)

### High Cardinality Features

In [93]:
pip install category_encoders

Requirement already satisfied: category_encoders in /opt/anaconda3/lib/python3.13/site-packages (2.11.1)
Requirement already satisfied: numpy>=1.14.0 in /opt/anaconda3/lib/python3.13/site-packages (from category_encoders) (2.1.3)
Requirement already satisfied: pandas>=1.0.5 in /opt/anaconda3/lib/python3.13/site-packages (from category_encoders) (2.2.3)
Requirement already satisfied: scikit-learn>=1.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from category_encoders) (1.15.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.0.5->category_encoders) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn>=1.6.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn>=1.6.0->category_encoders) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [94]:
# Perform target encoding on: ListOfficeName, CountyOrParish, HighSchoolDistrict, City, PostalCode, YearBuilt

to_encode_train = train_set[["ListOfficeName", "CountyOrParish", "HighSchoolDistrict", "City", "PostalCode", "YearBuilt"]]
to_encode_test = test_set[["ListOfficeName", "CountyOrParish", "HighSchoolDistrict", "City", "PostalCode", "YearBuilt"]]

encoder = TargetEncoder(smooth="auto", cv=5, random_state=42)

x_train_encoded = encoder.fit_transform(to_encode_train, train_set["ClosePriceLog"])
x_test_encoded = encoder.transform(to_encode_test)

x_train_encoded_df = pd.DataFrame(x_train_encoded, columns=to_encode_train.columns)
x_test_encoded_df = pd.DataFrame(x_test_encoded, columns=to_encode_train.columns)

train_set = train_set.join(x_train_encoded_df, rsuffix='_enc')
test_set = test_set.join(x_test_encoded_df, rsuffix='_enc')

## Summary

In [135]:
train_set.isna().sum()

ViewYN                    0
PoolPrivateYN             0
ListingKey                0
ClosePrice                0
Latitude                  0
Longitude                 0
LivingArea                0
ListOfficeName            0
CountyOrParish            0
AttachedGarageYN          0
ParkingTotal              0
YearBuilt                 0
ListingId                 0
BathroomsTotalInteger     0
City                      0
BedroomsTotal             0
FireplaceYN               0
Stories                   0
MainLevelBedrooms         0
NewConstructionYN         0
GarageSpaces              0
HighSchoolDistrict        0
PostalCode                0
AssociationFee            0
LotSizeSquareFeet         0
PropertyMonth             0
ClosePriceLog             0
LivingAreaLog             0
LotSizeSquareFeetLog      0
AssociationFeeLog         0
Bamboo                    0
Brick                     0
Carpet                    0
Concrete                  0
Laminate                  0
SeeRemarks                0
Stone                     0
Tile                      0
Unknown                   0
Vinyl                     0
Wood                      0
StateOrProvince_AZ        0
StateOrProvince_CA        0
StateOrProvince_CO        0
StateOrProvince_ME        0
StateOrProvince_NV        0
StateOrProvince_OS        0
StateOrProvince_TN        0
ListOfficeName_enc        0
CountyOrParish_enc        0
HighSchoolDistrict_enc    0
City_enc                  0
PostalCode_enc            0
YearBuilt_enc             0
dtype: int64

In [136]:
train_set.to_csv("week_3_train_2.csv", index=False)
test_set.to_csv("week_3_test_2.csv", index=False)

### Dataset Shape Per Stage

| Action | Shape | Dropped Rows | Dropped Row % | Dropped Cols | Dropped Col % |
| ------ | ------| ------------------| ------------- | -------------------- | ------- |
| Original | (309735, 83) | 0 | 0% | 0 | 0% |
| After Removing Columns | (309735, 33) | 0 | 0% | 50 | 60.24% |
| After Removing Rows | (309317, 32) | 418 | 0.13% | 1 | 3.03% |

| Train Action | Train Shape | Train Dropped Rows | Train Dropped Row % | Train Dropped Cols | Train Dropped Col % 
| ------ | ------| ------------------| ------------- | -------- | ----
| Original Split | (296586, 32) | 0 | 0% | 0 | 0%
| Handle Outliers | (266932, 32) | 29654 | 10.0% | 0 | 0
| Handle Missing Categorical Property Features | (266932, 32) | 0 | 0% | 0 | 0%
| Handle Missing Small Numerical Property Features | (266932, 31) |  0 | 0% | 1 | 3.13%
| Handle Missing Large Numerical Property Features | (266932, 29) | 0 | 0% | 2 | 6.45%
| Location Features | (265350, 29) | 1582 | 0.59% | 0 | 0%
| Scaling | (265350, 33) | 0 | 0% | + 4 | + 13.79%
| Encoding | (265350, 54) | 0 | 0% | 21 + | + 63.64%

| Train Action | Train Shape | Train Dropped Rows | Train Dropped Row % | Train Dropped Cols | Train Dropped Col % 
| ------ | ------| ------------------| ------------- | -------- | ----
| Original Split |  (12731, 32) | 0 | 0% | 0 | 0%
| Handle Outliers | (11390, 32) | 1341 | 10.53% | 0 | 0%
| Handle Missing Categorical Property Features | (11390, 32) | 0 | 0% | 0 | 0%
| Handle Missing Small Numerical Property Features | (11390, 31) | 0 | 0% | 1 | 3.12%
| Handle Missing Large Numerical Property Features | (11390, 29) | 0 | 0% | 2 | 6.45%
| Location Features | (11329, 29) | 61 | 0.54% | 0 | 0%
| Scaling | (11329, 33) | 0 | 0% | + 4 | + 13.79%
| Encoding | (11329, 49) | 0 | 0% | 21 + | + 63.64%

### Action Summary

| Dropped | No Change | Imputed | Filled with "Unknown" |
| -------- | -------- | -------- | -------- |
| FireplacesTotal | ListingKey | Stories | Flooring |
| CoveredSpaces | StateOrProvince | BathroomsTotalInteger | ViewYN |
| AboveGradeFinishedArea | BedroomsTotal | AssociationFee | PoolPrivateYN |
| TaxAnnualAmount| ListingId | LotSizeSquareFeet | AttachedGarageYN |
| TaxYear | CountyOrParish | MainLevelBedrooms | FireplaceYN |
| ElementarySchoolDistrict | PostalCode | YearBuilt | NewConstructionYN |
| BusinessType | ListOfficeName | LivingArea | HighSchoolDistrict |
| MiddleOrJuniorSchoolDistrict | CloseDate | ParkingTotal | |
| WaterfrontYN | ClosePrice | GarageSpaces |  |
| BelowGradeFinishedArea | | Longitude | |
| BasementYN | | Latitude | |
| BuilderName |  | City | |
| LotSizeDimensions | |  |  |
| BuildingAreaTotal | | | |
| CoBuyerAgentFirstName | | | |
| OriginatingSystemName | | | |
| OriginatingSystemSubName | | | |
| BuyerAgencyCompensation |  | | |
| BuyerAgencyCompensationType | | | |
| ElementarySchool | | | |
| MiddleOrJuniorSchool | | | |
| HighSchool | | | |
| CoListAgentFirstName | | | |
| CoListAgentLastName | | | |
| CoListOfficeName | | | |
| AssociationFeeFrequency | | | |
| lonfilled | | | |
| latfilled | | | |
| SubdivisionName | | | |
| OriginalListPrice | | | |
| ListPrice | | | |
| DaysOnMarket | | | |
| BuyerOfficeName | | | |
| BuyerAgentMlsId | | | |
| BuyerAgentFirstName | | | |
| BuyerAgentLastName | | | |
| MlsStatus | | | |
| BuyerOfficeAOR | | | |
| PurchaseContractDate | | | |
| BuyerAgentAOR | | | |
| ContractStatusChangeDate | | | |
| ListingContractDate | | | |
| ListAgentFirstName | | | |
| ListAgentLastName | | | |
| ListAgentAOR | | | |
| ListAgentEmail | | | |
| ListAgentFullName | | | |
| Levels | | | |
| LotSizeAcres | | | |
| LotSizeArea | | | |
| UnparsedAddress | | | |
| StreetNumberNumeric | | | |
| MLSAreaMajor | | | |
| ListingKeyNumeric | | | |
| PropertyType | | | |
| PropertySubType | | | |